### ISSUE TITLE
Easy to use, but..

### ISSUE THREAD

**Issue by jakehsiao0909** [nccgroup/aws-inventory#17]
I wanted to thank you that this tool provided what I need and very easy to use, but is there any way I can also get the "Last Modified Date" on the resources detail I got back in the JSON?

**Comment by bitsandsalsa** [comment]
That would be a great feature, but I don't think that is possible with the current design of the tool. That sort of detail is not included in the APIs from AWS.

It might be possible to use AWS logs or alerts or AWS Config to get that data though.

**Comment by ncc-erik-steringer** [comment]
Cleaning out issues. It looks like this isn't going to be possible to implement as desired, due to how this tool is designed + how AWS works. Right now, you do have the `run_date` field at the top-level of the output JSON, which can at least help give you an idea of how fresh the details are.

Closing.
